require('dotenv').config();
const express=require('express');
const cors=require('cors');
const helmet=require('helmet');
const morgan=require('morgan');
const rateLimit=require('express-rate-limit');
const path=require('path');
const app=express();
app.use(helmet({crossOriginResourcePolicy:false}));
app.use(cors());
app.use(express.json({limit:'2mb'}));
app.use(morgan('dev'));
app.use(rateLimit({windowMs:15*60*1000,limit:300}));
app.use('/uploads',express.static(path.join(__dirname,'../uploads')));
app.get('/health',(_,res)=>res.json({ok:true,name:'uabber-backend'}));
app.use('/api/auth',require('./routes/auth.routes'));
app.use('/api/categories',require('./routes/categories.routes'));
app.use('/api/items',require('./routes/items.routes'));
app.use('/api/subscriptions',require('./routes/subscriptions.routes'));
app.use('/api/consultations',require('./routes/consultations.routes'));
app.use('/api/journey-steps',require('./routes/journey.routes'));
app.use('/api/admin',require('./routes/admin.routes'));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({message:'Server error'});});
const port=process.env.PORT||4000;
app.listen(port,()=>console.log(`Uabber API running on http://localhost:${port}`));
